stages:
  - build
  - publish

cache:
  key: $CI_COMMIT_REF_SLUG
  policy: pull-push
  paths:
    - .npm/

build:
  image: node:lts
  stage: build
  before_script:
    - npm ci --cache .npm --prefer-offline
    - npm install --cache .npm --prefer-offline
  script:
    - npm run build

publish:
  image: node:lts
  before_script:
    - npm config set '//gitlab.com/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - npm config set '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
  stage: publish
  script:
    - npm publish
  only:
    - tags
