stages:
  - publish

cache:
  key: $CI_COMMIT_REF_SLUG
  policy: pull-push
  paths:
    - .npm/

publish:
  image: node:lts
  before_script:
    - npm config set '//gitlab.com/api/v4/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
    - npm config set '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken' "${CI_JOB_TOKEN}"
  stage: publish
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - npm publish
