name: Publish Pre-release
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
          registry-url: https://registry.npmjs.org
      - run: cat ./.npmrc
      - run: npm ci
      - run: npm publish --tag prerelease
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
