name: Publish Pre-release
on:
  push:
    tags-ignore:
      - "**"
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true
          registry-url: https://registry.npmjs.org
          cache: npm
      - run: npm ci
      - run: npm version prerelease --preid=dev
      - run: git push --follow-tags
      - run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
